"""initieel schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 19:42:44.570992

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.Column("email", sa.Unicode(length=320), nullable=False),
        sa.Column(
            "status",
            sa.Enum("actief", "inactief", name="memberstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Unicode(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
        sa.UniqueConstraint("email", name=op.f("uq_members_email")),
    )
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_members_name"), ["name"], unique=False)

    op.create_table(
        "subcategories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_subcategories_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subcategories")),
        sa.UniqueConstraint("category_id", "name", name="uq_subcategories_category_name"),
    )
    with op.batch_alter_table("subcategories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subcategories_category_id"), ["category_id"], unique=False
        )

    op.create_table(
        "donations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("subcategory_id", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("donated_at", sa.DateTime(), nullable=False),
        sa.Column("description", sa.Unicode(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Unicode(length=200), nullable=False),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_donations_amount_positive")),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f("fk_donations_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["subcategories.id"],
            name=op.f("fk_donations_subcategory_id_subcategories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_donations")),
    )
    with op.batch_alter_table("donations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_donations_donated_at"), ["donated_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_donations_member_id"), ["member_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_donations_subcategory_id"), ["subcategory_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_donations_subcategory_id"))
        batch_op.drop_index(batch_op.f("ix_donations_member_id"))
        batch_op.drop_index(batch_op.f("ix_donations_donated_at"))

    op.drop_table("donations")
    with op.batch_alter_table("subcategories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subcategories_category_id"))

    op.drop_table("subcategories")
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_members_name"))

    op.drop_table("members")
    op.drop_table("categories")
    # ### end Alembic commands ###
