"""logboek

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 23:37:52.149346

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ledenadmin.db

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", ledenadmin.db.UTCDateTime(), nullable=False),
        sa.Column("user", sa.Unicode(length=200), nullable=False),
        sa.Column("action", sa.Unicode(length=20), nullable=False),
        sa.Column("method", sa.Unicode(length=10), nullable=False),
        sa.Column("path", sa.Unicode(length=500), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("detail", sa.Unicode(length=2000), nullable=True),
        sa.Column("ip", sa.Unicode(length=64), nullable=True),
        sa.Column("user_agent", sa.Unicode(length=300), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_user"), ["user"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_user"))
        batch_op.drop_index(batch_op.f("ix_audit_log_at"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
