"""ledenvelden

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 00:13:35.831577

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ledenadmin.db

revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.Unicode(length=100), nullable=False),
        sa.Column("field_type", sa.Unicode(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_member_fields")),
        sa.UniqueConstraint("label", name=op.f("uq_member_fields_label")),
    )
    op.create_table(
        "member_field_values",
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Unicode(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["member_fields.id"],
            name=op.f("fk_member_field_values_field_id_member_fields"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f("fk_member_field_values_member_id_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("member_id", "field_id", name=op.f("pk_member_field_values")),
    )
    with op.batch_alter_table("member_field_values", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_member_field_values_field_id"), ["field_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("member_field_values", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_member_field_values_field_id"))

    op.drop_table("member_field_values")
    op.drop_table("member_fields")
    # ### end Alembic commands ###
